### ISSUE TITLE
Slots in distinct goroutine

### ISSUE THREAD

**Issue by tux-eithel** [tucnak/meta#1]
Hi!
Just a note...
You said

> Once a signal gets emitted, all the slots connected are being executed in the distinct goroutines.

And this is the Emit function

```
func (sig *Signal) Emit(data interface{}) {
    for i := 0; i < len(sig.cons); i++ {
        sig.cons[i].slot(&Call{Data: data})
    }
}
```

But I think that the function could be rewritten in this way

```
func (sig *Signal) Emit(data interface{}) {
    for i := 0; i < len(sig.cons); i++ {
        go func(c conn) {
            c.slot(&Call{Data: data})
        }(sig.cons[i])
    }
}
```

**Comment by tucnak** [comment]
Nice catch! I somehow managed to lose the `go` call in between commit.

**Comment by tux-eithel** [comment]
I'm here again :smile: !

Now that there is `go` function maybe it would be useful to give some "wait handler", otherwise your example doesn't print anything.

I  suggest to modify the `Emit` function in this way:

```
// Emit executes all the connected slots with data given.
func (sig *Signal) Emit(data interface{}) *sync.WaitGroup {
    wg := sync.WaitGroup{}
    wg.Add(len(sig.cons))

    for i := 0; i < len(sig.cons); i++ {
        go func(i int) {
            sig.cons[i].slot(&Call{Data: data})
            wg.Done()
        }(i)
    }

    return &wg
}
```

So in the main program you could wait (if you want/need) the end of signal propagation

```
wait := foo.Done.Emit(42)

// more lines of code...

wait.Wait()
```

If this goes beyond your example, just put a simple `time.Sleep(1 * time.Second)` to wait routines

**Comment by tucnak** [comment]
I'd do what I did in tests: emit signals from a goroutine:

``` go
go func() {
    <-time.After(10 * time.Millisecond)
    foo.Done.Emit()
}
```

It might be enough.

**Comment by tux-eithel** [comment]
Well, I think that `<-time.After(10 * time.Millisecond)` in the test doesn't anything useful, because program stops here `x := <-pipe` waiting for some data, so I don't understand where do you want to use.

**Comment by tucnak** [comment]
Oh, I just realized what you were talking about. Gimme a sec, looks like I'd need to redesign the whole thing.
